UVU-DigitalMedia/DGM-Competency-Browser

README.md
app/index.html
app/js/app.js
app/js/controllers.js
app/js/services.js
app/templates/about.html
app/templates/home.html
bower.json

Adding base information for routing, service, and controller to get the Angular functionality working.

Base Angular file information.

---

Gruntfile.js

Grunt seed

---

app/index.html
app/js/app.js
app/js/controllers.js
app/templates/tracks.html

I have pulled down the new changes and manually added the merge conflicts together. Hopefully there are no conflicts now.

Merge Conflict Fixed - I hope

---

app/css/styles.css
app/index.html
app/js/app.js
app/js/controllers.js
app/templates/courses.html
app/templates/skills.html
app/templates/tracks.html

Added skills section with basic information. Most likely will need to merge Sam's pull request prior to this one to hopefully avoid merge conflicts.

Skills tab creation

---

README.md

There is a new image now for that includes fixing conflicts before pull request. Also added a section about syncing to other forks. :wolf: 
Check the image to make sure the workflow works. Thanks! :+1:

Updated workflow image and syscing to other forks

---

Gruntfile.js
README.md

This will add the build status to to the readme.

Adding Travis Image to README

---

app/js/controllers.js
app/templates/tracks.html

I added in a modal to add a new semester, and modals to add a new course inside of a semester.

[axof: 211]

---

app/skills/skills.html
app/skills/skillsCtrl.js

Functionality to filter skills by checkboxes of each company, through an optional select dropdown box, or by typing the skill in a textbox.

Skills filtering

---

models/categories.js
models/jobs.js
models/skills.js

Hopefully I did this correctly. I'm not sure if these schema files need more than what I have so far. This information is based off of the json data that we had come up with. If this structure is not correct, just let me know and I will learn how to fix it!

added 3 mongoose schema files.

---

app/css/partials/_base.scss
app/css/partials/_footer.scss

Fixed issue where scrolling was broken. Made footer sticky. [axof: 224]

Footer & General Fixes

---

app/js/app.js
app/skills/skillsCtrl.js

Fixed app.js dependencies so that the skills section would work again.

Skills Page Fix

---

app/css/partials/_skills.scss
app/index.html
app/js/app.js
app/js/common/services/empResource.js
app/skills/skills.html
app/skills/skillsCtrl.js
bower.json

Added Angular UI Bootstrap to provide Angular/Bootstrap based functionality.

Angular UI Skills Functionality

---

app/courses/courses.html
app/css/partials/_base.scss
app/css/partials/_breadcrumbs.scss
app/css/partials/_variables.scss
app/index.html
app/js/jquery.js
app/skills/skills.html
app/templates/breadcrumbs.html
app/templates/courses.html
app/templates/home.html
app/tracks/tracks.html

Fixed breadcrumbs styles so not to include jQuery functionality.  Gave it simplier styles. [axof: 243]

Fixed breadcrumbs styles so not to include jQuery functionality.  Gave it simplier styles. [axof: 243]

---

app/css/partials/_skills.scss
app/index.html
app/js/common/services/empResourceMock.js
app/skills/skills.html

Moved search icon to the right side. [axof: 255]

Modified the search input box on the skills page for custom styling and better user interface. 

---

app/tracks/tracks.html

...SO MERGE THIS BEFORE YOU MERGE CAIT'S SO I DON'T HAVE TO RECOMMIT DUE TO MERGE CONFLICTS! I fixed the toggle so the semesters start closed for the toggle and they toggle correctly now. I also added in some of the already built classes to style the page a little bit more.

[axof: 250 wl: 3 hours] MERGE BEFORE CAIT'S SO I DON'T HAVE TO RECOMMIT BECAUSE I STILL HAVE GRUNT ERROR!

---

README.md
app/css/partials/_base.scss
app/index.html
app/js/app.js
app/js/controllers.js

Fixed issues with the navigation sign in form not working. First issue was the navigation controller. Removed that and moved information in that controller over to rootScope in the app.js. That means moving the login function over there to from the loginController. The navigation ng-ifs were also causing issues. Changed that to ng-show. Any login functionality since we are using a form that can be used on multiple pages NEEDS to be done through rootscope, else it will cause issues. Debugging this took me HOURS. [axof: 259]

Sign In Form Bug Fix

---

app/skills/skills.html
app/skills/skillsCtrl.js

Toggle class for favorite skills.

Skills favorites

---

app/css/partials/_skills.scss
app/skills/skills.html
app/skills/skillsCtrl.js

Changed skills favoriting to only select individual item.

Skills fav update

---

app/css/partials/_dashboard.scss
app/css/styles.scss
app/index.html
app/js/controllers.js
app/js/menu.js
app/templates/home.html

Created login version of dashboard.  Fixed mobile navigation. [axof: 273]

Created login version of dashboard.  Fixed mobile navigation. [axof: 273]

---

app/css/partials/_courses.scss
app/css/partials/_favorites.scss
app/css/styles.scss
app/js/controllers.js
app/templates/favorites.html

Style favorites page. [axof: 260]

Style favorites page. [axof: 260]

---

app/css/partials/_courses.scss
app/css/partials/_editProfile.scss
app/css/partials/_favorites.scss
app/css/partials/_profile.scss
app/css/styles.scss
app/js/app.js
app/js/controllers.js
app/templates/editProfile.html
app/templates/favorites.html
app/templates/profile.html

Added edit profile styles. [axof: 276]

Added edit profile styles. [axof: 276]

---

app/index.html

Removed about page link. [axof: 258]

Removed about page link. [axof: 258]

---

app/css/partials/_favorites.scss
app/templates/favorites.html

Updated favorites desc to open on click. [axof: 284]

Updated favorites desc to open on click. [axof: 284]
